apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: api-gateway
  namespace: consul
spec:
  gatewayClassName: consul-api-gateway
  listeners:
    - protocol: HTTP
      # fix: on the original tutorial documentation
      # (here: https://developer.hashicorp.com/consul/tutorials/get-started-kubernetes/kubernetes-gs-ingress#deploy-consul-api-gateway)
      # the port is "8443", which is... wrong?
      port: 8080
      name: https
      allowedRoutes:
        namespaces:
          from: Same
      tls:
        certificateRefs:
          - name: consul-server-cert
