apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: consul
  labels:
    app: ingress-gateway
spec:
  listeners:
    - port: 8888
      protocol: http
      services:
        - name: nginx
          hosts: ["nginx:80"]