apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: default
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
  namespace: default
spec:
  protocol: "http"
