global:
 enabled: true
 name: consul
 datacenter: dc1

 metrics:
  enabled: true

 tls:
  enabled: true

 acls:
  manageSystemACLs: true

controller:
 enabled: true

server:
 enabled: true
 replicas: 1

connectInject:
 enabled: true

prometheus:
 enabled: true

ui:
 enabled: true
 service:
  type: NodePort


































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































