global:
  image: hashicorp/consul:1.14.2
  enabled: true
  name: consul
  datacenter: dc1

  metrics:
    enabled: true

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true

  acls:
    manageSystemACLs: true

controller:
  enabled: true

server:
  enabled: true
  replicas: 1

connectInject:
  enabled: true

prometheus:
  enabled: true

ui:
  enabled: true
  service:
    type: ClusterIP

ingressGateways:
  enabled: true
  defaults:
    affinity: null
  gateways:
    - name: ingress-gateway
      service:
        type: ClusterIP
        ports:
          - port: 8888
      replicas: 1